### PR TITLE
Dockerfile: read version from project

### PR DESCRIPTION
**Pull request by eguzki**
The goal is to install a given version in a docker container. 

The version is read from a file in the repo. 

Fix https://github.com/3scale/3scale_toolbox/issues/74

### CODE REVIEW

**Comment by eguzki** [comment]
@unleashed any idea to do it better?

**Comment by unleashed** [comment]
Barring the possibility to evaluate that code with Ruby, my 0.02¢ is that I'd harden the spec with grep so that it matches just one line (the first) and the start of the line and the version matches `\d+\.\d+\.\d+.*'$` - I'd also add a comment above not to break this expectation, just in case.

**Comment by eguzki** [comment]
I was wondering if quay.io pushed some info on building like tag via `--build-arg`. Then I could have something like
```
ARG VERSION=default_version
```

**Comment by unleashed** [comment]
not as far as I know - I'd like for them to pass in the git ref but no luck.

**Pull request merged**
